### ISSUE TITLE
Turn the whole project into a PR for FSharp.Data

### ISSUE THREAD

**Issue by giacomociti** [fsprojects/FSharp.Data.Xsd#2]
I really would like some feedback here, especially because reading the [recommended guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html) I'm not sure if this project qualifies for having the FSharp namespace.
I opted for a separate project to avoid interfering with a [similar attempt](https://github.com/fsharp/FSharp.Data/issues/57); but also because I like the idea of immediately shipping something useful, albeit maybe not tested enough for such a mature and popular library which is FSharp.Data.

**Comment by toburger** [comment]
I think a Type Provider qualifies perfectly for the FSharp.* namespace.
The separation from FSharp.Data is a good choice for the moment until the implementation is more mature. Later a merge into FSharp.Data could be considered.
