### ISSUE TITLE
Lazy Streaming?

### ISSUE THREAD

**Issue by Rickasaurus** [fsprojects/FSharp.Data.Xsd#22]
### Description

We tend to work with super big XML files and it would be so nice to be able to stream them lazily with this.

### Repro steps

No problem, just a suggestion

### Actual behavior

So I think an IEnumerable with a bunch of optional components for all of the top level types would work, I'm up for anything here. 

### Known workarounds

Buy more ram 

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by giacomociti** [comment]
This is more or less the same request of #12 and of  course it makes sense, especially the pragmatic idea of limiting it to top level items. Implementation may not be trivial though, at least for me, but of course PRs are more than welcome

**Comment by Rickasaurus** [comment]
I would love to contribute if I could find some time.

**Comment by giacomociti** [comment]
the following [gist](https://gist.github.com/giacomociti/5568a8016182e8656cdd45681292dd2b) may be handly for someone looking for a way to turn a huge xml file into a lazy sequence of elements. The missing step is then to map each `XElement` with the ctor of the corresponding type generated by the type provider

**Comment by giacomociti** [comment]
I'm closing this because XSD is now available in F# Data and we may further discuss things there.
