### ISSUE TITLE
Problem with loading of elements of xml file when schema is build with xsd file

### ISSUE THREAD

**Issue by Etschbeijer** [fsprojects/FSharp.Data.Xsd#23]
### Description

Hi,
I started working with xml files before a short time and was using FSharp.data without FSharp.Data.Xsd and I had no problem, when I tried to pick specific elements form the file.
But the used scheme is quite complex and I hoped to avoid rewriting it completely to a xml file because a xsd file is available.
When I used the FSharp.Data.Xsd everything seemed to work properly because the whole file was loaded as normal but when I tried to pick a specific element the array was always empty or not existing (None).

### Repro steps
I thought giving you the code I worked with is sufficient.
Calling the Information of the whole file is no problem but upon calling for specific elements the output is always empty or not existing (None).

#r @"..\packages\FSharp.Data.2.4.6\lib\net45\FSharp.Data.dll"
#r @"..\packages\FSharp.Data.Xsd.1.0.2\lib\net45\FSharp.Data.Xsd.dll"
#r "System.Xml.Linq.dll"

open FSharp.Data

//type SchemeTest = XmlProvider<"..\ExampleFile\Test.txt">
//let  sampleTest = SchemeTest.Load("..\ExampleFile\Test.txt")
//sampleTest

type SchemePeptideShaker = XmlProvider<Schema = "..\ExampleFile\MzIdentMLScheme.xsd">
let  samplePeptideShaker = SchemePeptideShaker.Load("..\ExampleFile\PeptideShaker_mzid_1_2_example.txt")

samplePeptideShaker

samplePeptideShaker.CvList
    |> Array.map (fun cvItem -> cvItem)

### Expected behavior

I should give me an array of the different cvItems of the CvList.

### Actual behavior

Calling for the cvItems of the CvList results in an empty array.

### Known workarounds

When I do not work with the xsd file but with the xml file there is no problem but the example file is incomplete.

### Related information 

* Microsoft Visual Studio 2017 
* https://fsprojects.github.io/FSharp.Data.Xsd/
The files that were used (could not uploadthe whole file but this one shoulb be sufficient for the cCvList test.)
[MzIdentMLScheme - Copy.txt](https://github.com/fsprojects/FSharp.Data.Xsd/files/1947923/MzIdentMLScheme.-.Copy.txt)

[PeptideShaker_Scheme.txt](https://github.com/fsprojects/FSharp.Data.Xsd/files/1947924/PeptideShaker_Scheme.txt)

* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by giacomociti** [comment]
I think there is a version mismatch between your xml document and the schema: you are using version 1.1.1 of the schema but the document is built according to version 1.2.0.
And the namespaces don't match, so the type provider does not recognize any element.
Try to use an updated schema

**Comment by Etschbeijer** [comment]
That was the problem, thank you did not notice it by myself.
