### ISSUE TITLE
New "xs:date" XSD types are including time info from .NET DateTime values

### ISSUE THREAD

**Issue by gtbremer** [fsprojects/FSharp.Data.Xsd#24]
### Description

If an XSD schema document has an element or attribute that is defined as "xs:date" type, the FSharp.Data.Xsd library puts DateTime values ("xs:dateTime") instead of date-only values. 

Please note that I am explicitly referring to the MySchemaType.MyElement(prop1 = someValue;) method of creating objects. In this case, if prop1 is defined in the XSD as "xs:date", passing a .NET DateTime value in will result in the XElement being created with date and time information...when, acccording to the XSD document, it should be only a date value.

When creating new objects using MySchemaType.MyElement(XElement) works correctly...but only if the XElement already has the correct syntax (i.e., uses a Date-only value rather than DateTime value).  I do not necessarily expect that the library will fix invalid XElement values in this situation, although it might be nice to raise some sort of warning. Overall, I expect the library to adhere to the type definitions in the XSD document and inserting date+time when the XSD explicitly defines date-only values is incorrect behavior.

### Repro steps
```
#r "System.Xml.Linq.dll"
#r "FSharp.Data.Xsd.dll"

open System
open FSharp.Data

type Sample = XmlProvider<Schema = """
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="foo">
      <xs:complexType>
        <xs:attribute name="baz" type="xs:date" />
      </xs:complexType>
    </xs:element>
  </xs:schema>""">

let createUsingProps : Sample.Foo = Sample.Foo( DateTime.Now.Date |> Some )
let createUsingXelement : Sample.Foo = Sample.Parse """<foo baz="2018-05-02" />"""


createUsingProps.XElement |> sprintf "Using props method:\n%A"
createUsingXelement.XElement |> sprintf "Using XElement method:\n%A"

(*
> 
val it : string =
  "Using props method:
<foo baz="2018-05-02T00:00:00.0000000-04:00" />"
> 
val it : string = "Using XElement method:
<foo baz="2018-05-02" />"
> 
*)
```

### Expected behavior

That the library would use the"xs:date" type defined in the XSD document when creating new objects.

### Actual behavior

The library actually uses a "xs:datetime" type when creating new objects using properties.

### Known workarounds

Creating new objects using MySchemaType.MyElement(XElement) works correctly...but only if the XElement already has the correct syntax (i.e., uses a Date-only value rather than DateTime value).

### Related information 
* .NET Framework: 4.5.2
* FSharp.Data.Xsd: 1.0.2.0
* Windows 10 operating system
```

**Comment by Rickasaurus** [comment]
I think this may be a bug coming from one of the FSharp.Data XML References.

**Comment by gtbremer** [comment]
Wow, okay,...I knew that .NET lacks a Date-only type (I think NodaTime adds one) but I didn't know that Microsoft didn't even have a standard way of dealing with date-only types defined in XSDs. Interesting.

Will using a string type introduce date format issues with regards to localization, etc.?

**Comment by Rickasaurus** [comment]
Date seems pretty standard and easy to output as if it were a string https://www.w3schools.com/xml/schema_dtypes_date.asp

**Comment by giacomociti** [comment]
I'm closing this because XSD is now available in F# Data (where some improvements have been made on date handling).
