### ISSUE TITLE
Please give an example on how to generate XML having complex XSD

### ISSUE THREAD

**Issue by TonyHenrique** [fsprojects/FSharp.Data.Xsd#26]
I need to see an example of how to generate XML having this complex XSD (zipped file):

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=xLaRDcJryNA=

With that ZIP file contents, today in C# we can use

`xsd.exe nfe_v4.00.xsd xmldsig-core-schema_v1.01.xsd /c /edb`

Here in Brazil XSD Schemas are being used heavily. 

Right now that governament portal indicates 19394 billion documents generated using those XSD schemas.

**How to generate XML having those XSD, using F# ?**

**Comment by giacomociti** [comment]
what root element are you trying to create?

**Comment by TonyHenrique** [comment]
The root element I want is this:
<xs:element name="NFe" type="TNFe">

In C# I used this:

```
var nfe = new TNFe();
nfe.infNFe.emit = new TNFeInfNFeEmit()
{
    xNome = "GR5"
};

```

**Comment by giacomociti** [comment]
Inside `xmldsig-core-schema_v1.01.xsd` the only element I see is `Signature`

**Comment by giacomociti** [comment]
I'm closing this because XSD is now available in F# Data and we may further discuss things there.
